CREATE ROLE heroku;
ALTER ROLE heroku WITH LOGIN PASSWORD 'password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE DATABASE iptracker OWNER heroku;
REVOKE ALL ON DATABASE iptracker FROM PUBLIC;
GRANT CONNECT ON DATABASE iptracker TO heroku;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO heroku;